model:
  path: "weights/parkinsons_detector_gemma3n"
  temperature: 0.7
  max_new_tokens: 200

audio:
  sample_rate: 16000
  channels: 1
  recording_dir: "recordings"

therapy:
  exercises:
    sustained_vowel:
      duration: 5
      description: "Sustain the vowel 'ahhhh' for 5 seconds"
      target_pitch: 220  # Hz (A3 note)
      
    word_repetition:
      duration: 10
      description: "Repeat the following words clearly: 'blue, green, red'"
      words: ["blue", "green", "red"]
      
    loudness_training:
      duration: 5
      description: "Say 'Strong voice!' with increasing volume"
      target_db: 75
      
    rate_control:
      duration: 15
      description: "Count from 1 to 10 slowly and clearly"
      target_rate: 2  # words per second

thresholds:
  jitter: 0.02
  shimmer: 0.1
  pitch_variation: 50  # Hz
  harmonic_ratio: 20
  clarity: 0.7
  stability: 0.7
  volume: 0.6